services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: jabo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: jabo
      POSTGRES_PASSWORD: jabo
      POSTGRES_DB: jabo
    ports:
      - "5432:5432"
    volumes:
      - jabo_pg:/var/lib/postgresql/data

volumes:
  jabo_pg:
